project:
  type: website
  output-dir: docs

website:
  title: "Taehwan (Jack) Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Analysis
        menu:
          - href: case_study_1.qmd
            text: Success in Olympics
          - href: case_study_3.qmd
            text: Netflix Movies
          - href: Project_3.qmd
            text: NYC Flights Analysis
          - href: Project_4.qmd
            text: Wideband Acoustic Immittance Analysis
      - text: Sports
        menu:
          - href: case_study_2.qmd
            text: Referee Decisions in Soccer
      - text: Presentations
        menu: 
          - href: Project_5.qmd
            text: Flight Delays
      
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: source

