project:
  type: website
  output-dir: docs

website:
  title: "Taehwan (Jack) Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Data Viz
        menu:
          - href: case_study_1.qmd
            text: Case 1
          - href: case_study_2.qmd
            text: Case 2
          - href: case_study_3.qmd
            text: Case 3
      - text: Mini Projects
        menu:
          - href: Project_3.qmd
            text: Project 3
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

