---
title: "Taehwan (Jack) Kim | 김태환"
---

My life so far...

## Education

Pomona College - Claremont, California, USA

+ Major in Economics and Minor in Data Science
+ Resident of Clark I

Chadwick International School - Incheon, South Korea

+ Full IB Diploma
+ Higer Levels: Language & Literature, Global Politics, History
+ Standard Levels: Biology, Math, Spanish

Dankook University Middle School - Seoul, South Korea 

+ 2 years of extremely rigorous grind at the hub of Korean education
+ Only-boys middle school
+ Endless hours of private academies (hagwons)

Daedo Elementary School - Seoul, South Korea

+ 5 years of extremely rigorous grind at the hub of Korean education
+ Endless hours of private academies (hagwons)

Transit Middle School - Buffalo, New York, USA

+ Wonderful break from Korean education
+ A taste of cheerful life in US

Country Parkway Elementary School - Buffalo, New York, USA

+ Freedom from Korean education in a peaceful town in Buffalo


## Work Experience

Korea Search Fund

+ Crucial part of a live deal
+ Working currently in Korean hours

Tortoise Capital Management

+ Developed a passion for value investing
+ Birth of a stock guru

Kim & Chang Law Firm

+ Experienced the challenges of M&A deals
+ Importance of connections in completing business deals

DoOne Accounting Corporation

+ Entire global financial system is powered by Excel 2021
+ Work, Drink, Work more culture in Korea


## Activities & Achievements

Student Unior for Reasonable Investment (SURI)

+ Executive Investment Manager of $1 million portfolio

Certified Investment Manager

+ Certified by Korean Financial Investment Association (KOFIA)


## Soccer Career

Daedo Elementary (2009-2013)

Sinjeong Elementary (2012)

Dakook Middle (2014-2015)

Chadwick International Varsity Soccer (2016-2020)

Siheung FC U16, U17 (2015-2018)

Songdo FC (2015-2020)

Pomona-Pitzer Varsity Soccer (2020-2022)


## Military Experience

Repubic of Korea Army: Army Special Forces Reconnaissance Unit of 39th Infantry Brigade of 15th Infantry Division of Army 2nd Corps

+ Classified missions
