---
title: "Case Analysis 2: Premier League 2021-2022"
description: |
  Referees in Arsenal's Fixtures
author: Jack Kim
date: September 18, 2024
format: html

---

TidyTuesday Reference: https://github.com/rfordatascience/tidytuesday/tree/master/data/2023/2023-04-04

Original Data Source: https://www.kaggle.com/datasets/evangower/premier-league-match-data

Objective of the Analysis: Which referee gave out the most yellow cards to Arsenal during the 2021-2022 season?

As a lifelong Arsenal fan, I wanted to find out which referees tend to be harsher on Arsenal.

```{r}
library(tidytuesdayR)

tuesdata <- tidytuesdayR::tt_load('2023-04-04')
tuesdata <- tidytuesdayR::tt_load(2023, week = 14)

soccer <- tuesdata$soccer
```
```{r}
library(tidyverse)

arsenal_yellow_by_referee <- soccer |>
  filter(HomeTeam == "Arsenal" | AwayTeam == "Arsenal") |>
  group_by(Referee) |>
  summarise(
    Home_Yellow_Cards = sum(HY[HomeTeam == "Arsenal"], na.rm = TRUE),
    Away_Yellow_Cards = sum(AY[AwayTeam == "Arsenal"], na.rm = TRUE),
    Total_Yellow_Cards = Home_Yellow_Cards + Away_Yellow_Cards
  ) |>
  arrange(desc(Total_Yellow_Cards))


arsenal_yellow_by_referee

```
```{r, fig.height=5, fig.width=6}
library(ggplot2)

ggplot(arsenal_yellow_by_referee, aes(x = reorder(Referee, -Total_Yellow_Cards), y = Total_Yellow_Cards)) +
  geom_bar(stat = "identity", fill = "yellow") +
  geom_text(aes(label = Total_Yellow_Cards), vjust = -0.5, size = 4) +
  labs(title = "Yellow Cards Arsenal Received by Referees (2021-2022 Season)", 
       x = "Referee", 
       y = "Total Yellow Cards") +
  scale_y_continuous(breaks = NULL) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10), 
    axis.text.y = element_blank(),  
    axis.ticks.y = element_blank(), 
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()  
  )
```
Craig Pawson handed out the most yellow cards to Arsenal.
